[package]
name = "advent_of_code_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itermore = "0.1.0"
itertools = "0.10.3"
array2d = "0.2.1"
bitvec = "0.22.3"
derive_more = "0.99.17"